package com.luizalabs.integracao_logistica.core.exceptions

class AlreadyExistsUserWithThisOrderParseException: MainException("Already exists user with this order.")